package com.SwanHack2025.Default.Images;

import com.SwanHack2025.Default.Courses.Course;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ImageTest {

    private Image image;
    private Course course;

    @BeforeEach
    void setUp() {
        image = new Image();
        course = new Course("Test Course", "Test Description", "preview.jpg");
    }

    @Test
    void testImageCreationWithNoArgConstructor() {
        Image img = new Image();

        assertNotNull(img);
        assertNull(img.getId());
        assertNull(img.getPath());
        assertEquals(500,img.getImgElo());
        assertNull(img.getCourse());
        assertNull(img.getIsAi());
    }

    @Test
    void testImageCreationWithPathConstructor() {
        Image img = new Image("path/to/image.jpg");

        assertNotNull(img);
        assertEquals("path/to/image.jpg", img.getPath());
        assertEquals(500, img.getImgElo());
    }

    @Test
    void testDefaultEloIs500() {
        Image img = new Image("path/to/image.jpg");
        assertEquals(500, img.getImgElo());
    }

    @Test
    void testSettersAndGetters() {
        image.setId(1L);
        image.setPath("images/test.png");
        image.setImgElo(750);
        image.setIsAi(true);
        image.setCourse(course);

        assertEquals(1L, image.getId());
        assertEquals("images/test.png", image.getPath());
        assertEquals(750, image.getImgElo());
        assertTrue(image.getIsAi());
        assertEquals(course, image.getCourse());
    }

    @Test
    void testPathSetter() {
        image.setPath("test/path/image.jpg");
        assertEquals("test/path/image.jpg", image.getPath());
    }

    @Test
    void testImgEloCanBeUpdated() {
        image.setImgElo(500);
        assertEquals(500, image.getImgElo());

        image.setImgElo(1200);
        assertEquals(1200, image.getImgElo());
    }

    @Test
    void testImgEloCanBeNegative() {
        image.setImgElo(-100);
        assertEquals(-100, image.getImgElo());
    }

    @Test
    void testIsAiCanBeTrue() {
        image.setIsAi(true);
        assertTrue(image.getIsAi());
    }

    @Test
    void testIsAiCanBeFalse() {
        image.setIsAi(false);
        assertFalse(image.getIsAi());
    }

    @Test
    void testIsAiCanBeNull() {
        image.setIsAi(null);
        assertNull(image.getIsAi());
    }

    @Test
    void testCourseRelationship() {
        assertNull(image.getCourse());

        image.setCourse(course);
        assertNotNull(image.getCourse());
        assertEquals(course, image.getCourse());
        assertEquals("Test Course", image.getCourse().getName());
    }

    @Test
    void testCourseCanBeChanged() {
        Course course1 = new Course("Course 1", "Description 1", "preview1.jpg");
        Course course2 = new Course("Course 2", "Description 2", "preview2.jpg");

        image.setCourse(course1);
        assertEquals(course1, image.getCourse());

        image.setCourse(course2);
        assertEquals(course2, image.getCourse());
    }

    @Test
    void testCourseCanBeSetToNull() {
        image.setCourse(course);
        assertNotNull(image.getCourse());

        image.setCourse(null);
        assertNull(image.getCourse());
    }

    @Test
    void testImageWithAllProperties() {
        Image img = new Image("path/to/image.jpg");
        img.setId(1L);
        img.setImgElo(800);
        img.setIsAi(false);
        img.setCourse(course);

        assertEquals(1L, img.getId());
        assertEquals("path/to/image.jpg", img.getPath());
        assertEquals(800, img.getImgElo());
        assertFalse(img.getIsAi());
        assertNotNull(img.getCourse());
    }

    @Test
    void testPathCannotBeChanged() {
        image.setPath("original/path.jpg");
        assertEquals("original/path.jpg", image.getPath());

        image.setPath("new/path.jpg");
        assertEquals("new/path.jpg", image.getPath());
    }

    @Test
    void testEloRatingBoundaries() {
        // Test very low ELO
        image.setImgElo(0);
        assertEquals(0, image.getImgElo());

        // Test very high ELO
        image.setImgElo(3000);
        assertEquals(3000, image.getImgElo());

        // Test negative ELO
        image.setImgElo(-500);
        assertEquals(-500, image.getImgElo());
    }

    @Test
    void testIdIsAutoGenerated() {
        // In actual database context, ID should be auto-generated
        assertNull(image.getId());

        // Simulating what happens after saving to database
        image.setId(1L);
        assertNotNull(image.getId());
    }
}